name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          PROJECT_DIR=/home/ubuntu/todo_backend
          REPO_URL=https://github.com/MurungaOwen/todo-backend.git

          sudo apt update
          sudo apt install -y python3 python3-venv python3-pip git

          if [ ! -d "$PROJECT_DIR" ]; then
            git clone $REPO_URL $PROJECT_DIR
          fi

          cd $PROJECT_DIR

          git fetch --all
          git reset --hard origin/main

          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          # Environment variables - create .env file or export inline
          echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
          
          # Run migrations & collectstatic
          python manage.py migrate
          python manage.py collectstatic --noinput

          # Restart Gunicorn service (you can create a systemd service for gunicorn)
          sudo systemctl restart gunicorn || echo "Gunicorn service restart failed. Check service status."

          # Optional fallback: start gunicorn manually
          # pkill gunicorn || true
          # nohup venv/bin/gunicorn todo_backend.wsgi:application --bind 0.0.0.0:8000 &
